import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "./components/navbar/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar
  bgColor="#680b0b"
  className="rounded-lg"
  links={[
    {
      href: '/',
      name: 'Home'
    },
    {
      href: '/about',
      name: 'About'
    },
    {
      href: '/contact',
      name: 'Contact'
    }
  ]}
  logoAlt=""
  logoSrc="https://www.adaptivewfs.com/wp-content/uploads/2020/07/logo-placeholder-image.png"
  shadow="large"
  shadowColor="rgba(255, 255, 255, 0.2)"
  title=""
/>
        {children}
      </body>
    </html>
  );
}
